name: Deploy to github pages.
on:
  push:
    branches: [ hexo-source ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3.1.1
        with:
          node-version: '12.x'

      # Runs a set of commands using the runners shell
      # git submodule update --remote --merge
      - name: Before install
        run: |
          sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
          git submodule update --init --recursive
          npm install
          
      - name: Install
        run: |
          npm run clean
          npm run build -d
          
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: master
          keep_history: true
          allow_empty_commit: false
          build_dir: public
          jekyll: false
          committer: git-action-deploy
          commit_message: "git action deployed."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
