name: Deploy to github pages and azure static web app.
on:
  push:
    branches: [ stable-source ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3.1.1
        with:
          node-version: '19.x'

      # Runs a set of commands using the runners shell
      # git submodule update --remote --merge
      - name: Before install
        run: |
          sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
          git submodule update --init --recursive
          git submodule update --remote --merge
          npm install
          
      - name: Install
        run: |
          npm run clean
          npm run build -d
          
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: master
          keep_history: true
          allow_empty_commit: false
          build_dir: public
          jekyll: false
          committer: git-action-deploy
          commit_message: "git action deployed."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Deploy azure
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "/" # App source code path
          api_location: "/api" # Api source code path - optional
          output_location: "/public" # Built app content directory - optional
